server:
    port: 8001
spring:
    application:
        name: user-service
    datasource:
        url: jdbc:postgresql://localhost:5433/user-test
        username: postgres
        password:
        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    sql:
        init:
            mode: always
            data-locations: classpath:sql-test/clear-user-db.sql, classpath:sql-test/populate-user-db.sql
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: user-test
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
    instance:
        hostname: localhost
